# Generated by Django 4.2.4 on 2023-09-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code_verification',
            field=models.IntegerField(blank=True, null=True, verbose_name='Код верификации'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Проверка'),
        ),
    ]
