# Generated by Django 4.2.4 on 2023-09-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_code_verification_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_verification',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Код верификации'),
        ),
    ]
