# Generated by Django 4.2.4 on 2023-08-22 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_news_photo_alter_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Публикация статьи'),
        ),
    ]
